name: floatit

description: >
  FloatIT: Event management app for ITU, inspired by coffeecard_app structure.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  url_launcher: 6.3.1
  markdown: ^7.3.0
  flutter_markdown: ^0.6.18
  shared_preferences: ^2.0.18
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_cloud_firestore: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/privacy_policy.md
    - assets/login_bg.jpg
    - assets/signup_bg.jpg
    - assets/float_it.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/static/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic

flutter_icons:
  web:
    generate: true
    image_path: assets/float_it.png
