name: Deploy Dev Build to GitHub Pages

on:
  push:
    branches: [ dev ]
    paths:
      - 'lib/**'
      - 'web/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'analysis_options.yaml'
      - '.github/workflows/deploy-dev.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-dev"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build web (dev)
        run: flutter build web --release --base-href="/${{ github.event.repository.name }}/dev/" --dart-define=VAPID_KEY="${{ secrets.VAPID_KEY }}"

      - name: Copy service worker to output root
        run: cp web/firebase-messaging-sw.js build/web/firebase-messaging-sw.js

      - name: Deploy to GitHub Pages /dev
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          destination_dir: dev
          keep_files: true
