name: Send Notifications

on:
  schedule:
    # Run every 5 minutes (GitHub Actions cron uses UTC)
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./functions
        run: npm ci

      - name: Write service account
        env:
          SERVICE_ACCOUNT: ${{ secrets.FCM_SERVICE_ACCOUNT }}
        run: |
          if [ -z "$SERVICE_ACCOUNT" ]; then
            echo "No service account secret found (set FCM_SERVICE_ACCOUNT)";
            exit 1;
          fi
          echo "$SERVICE_ACCOUNT" > functions/service-account.json

      - name: Run notification sender
        working-directory: ./functions
        run: npm run start
